### ISSUE TITLE
Some Android devices can't access tic files without rooted phone

### ISSUE THREAD

**Issue by rubensoleao** [nesbox/TIC-80#2222]
The default folder in which tic80 saves is in `Android/data/com.nesbox.tic80/`, but not all phones have access to those folders without rooting the phone. In my case I have a motorola edge 20 running android 12, and can't access the files even when using file transfer connected to my PC.

I think this should be a bug because saved files, exports and imports can't be accessed on some phones.

What do you think? Is there plans on changing this directory?
Thanks

**Comment by sogaiu** [comment]
Perhaps it's better to rephrase:

> I think this should be a bug

I agree with bztsrc and wouldn't classify this as a TIC-80 bug, however, regarding:

> May I suggest to close this ticket as this isn't a TIC-80 bug? 

Though I wouldn't classify this as a TIC-80 bug, I think even if it isn't, may be it's worth leaving the issue open.

The default when searching issues is to have `is:open` as part of the query which means that people are less likely to come across this issue if they face a similar situation and search for an existing issue.

Also, I think making this issue more likely to be seen increases the chances someone with the inclination and motivation to provide a patch might do so.  I suspect that closing it means the probability of:

> Unless someone volunteers to implement some kind of workaround on buggy phones

would be even lower than not.

My two cents having sufferred a certain amount of pain from Android development and use :P

**Comment by bztsrc** [comment]
@sogaiu: Yeah, my phrasing was terrible, sorry about that.

I agree with you, and that's what I was trying to say: only keep this ticket open if we expect some black-belt Android dev to create a workaround for buggy phones.

Unfortunately I'm not that, using `SDL_AndroidGetExternalStoragePath` is the best I can think of, so no clue :-(

Cheers,
bzt

**Comment by rubensoleao** [comment]
A small correction to my issue, I actually do have access to the folder but I can't see the files saved in it (with usb or another app). This is also true for other apps.

But I don't think it's a faulty implementation on motorola's Android, and in some cases it is even more aligned to the android specification. in a lot of places in the documentation the directory used is cited to be "private" for the application. So probably it is a conscious choice to hide these files

Example in [Context::getExternalFilesDir](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)):
> These files are internal to the applications, and not typically visible to the user as media.

Or in [this table](https://developer.android.com/training/data-storage) it is said that `getExternalFilesDir()` cannot be accessed by other apps.

Going by the table cited above, it seems that the [Documents and other files](https://developer.android.com/training/data-storage/shared/documents-files) API is more suited, because it is accessible through the system file picker and files are not removed after app uninstall.

**Comment by rubensoleao** [comment]
I tested again on my devices, my motorola implements the behaviour cited in the table ( no access and deletes the files after uninstall ) and my Xiaomi tablet doesn't ( I can access the files  and they  are maintained after uninstall ).

**Comment by bztsrc** [comment]
> A small correction to my issue, I actually do have access to the folder but I can't see the files saved in it

Now this is a different issue, and indeed, this might be TIC-80's fault. I'm thinking maybe [main.c:1323](https://github.com/nesbox/TIC-80/blob/main/src/system/sdl/main.c#L1323) should be
```diff
        strcpy(appFolder, SDL_AndroidGetExternalStoragePath());
        const char AppFolder[] = "/" TIC_NAME "/";
        strcat(appFolder, AppFolder);
-        mkdir(appFolder, 0700);
+        mkdir(appFolder, 0777);
```
Assuming the application runs under a different unix user than the adb server, then this might fix it. But I'm not sure, and it would require a complete reinstall, because it has to remove the directory and re-create it again with different unix permissions.

> Going by the table cited above, it seems that the Documents and other files/Storage Access Framework is more suited

I'm guessing you're referring to [getMediaUri](https://developer.android.com/reference/android/provider/MediaStore#getMediaUri\(android.content.Context,%20android.net.Uri\)) from that page? That's not a bad idea. Unfortunately SDL doesn't have a function for that (see [API](https://wiki.libsdl.org/SDL2/CategoryAPI), functions starting with `SDL_AndroidGet...`). There should be a support in SDL first (but after that, should be straightforward to use it from TIC-80).

> I tested again on my devices, my motorola implements the behaviour cited in the table ( no access and deletes the files after uninstall ) and my Xiaomi tablet doesn't ( I can access the files and they are maintained after uninstall ).

Yep, I'm sure that directory supposed to be removed after uninstall. And I believe that's the expected behaviour, because what are you gonna do with some .tic files in lack of a TIC-80 application?

Cheers.
bzt

**Comment by rubensoleao** [comment]
@bztsrc I'l try changing it and see if it works in my phone and get back to this issue

**Comment by MuubNito** [comment]
> @bztsrc I'l try changing that line and see if it works in my phone and get back to this issue

Did it work?

**Comment by Timofei302** [comment]
I join the discussion. The problem is about the same, but I have access to the TIC-80 folder, but it is impossible to copy anything into it.
![1689795365-picsay](https://github.com/nesbox/TIC-80/assets/59145732/993052b6-7592-48f6-910f-82221f3f27ae)
But at the same time copying files to the folder above works
![Screenshot_20230719-222949](https://github.com/nesbox/TIC-80/assets/59145732/1667dbfd-4df6-435d-b6b0-00890c0d7abd)

**Comment by Timofei302** [comment]
After performing a couple of actions, it turned out that the TIC80 folder is not available for reading, and not only for writing.
![Screenshot_20230720-221500](https://github.com/nesbox/TIC-80/assets/59145732/6588f276-8e9e-48f3-99d6-a08db36cf632)
![Screenshot_20230720-221525](https://github.com/nesbox/TIC-80/assets/59145732/80f94488-84e8-4674-9f47-c54bdae7cd30)

**Comment by andreyorst** [comment]
For some apps, this folder can be accessed from a PC, but not for TIC:

![image](https://github.com/nesbox/TIC-80/assets/19470159/9592c447-c41d-4d85-b41b-458fa657182c)

**Comment by sogaiu** [comment]
I confirmed @andreyorst's report using the [latest release](https://github.com/nesbox/TIC-80/releases/tag/v1.1.2729).

May be it's worth trying the change suggested [here](https://github.com/nesbox/TIC-80/issues/2222#issuecomment-1620515377).

**Comment by sogaiu** [comment]
I gave it a try and it seems to have worked (note that it may be important to uninstall an existing TIC-80 app first so that the relevant directory is recreated -- though before doing this it might be good to copy any cart code via the editor and paste it somewhere else to prevent loss of data).

Below is some output from interacting via `adb shell`:

```
$ adb shell
gts8pwifi:/ $ ls -al /sdcard/Android/data/com.nesbox.tic/files/TIC-80
total 172
drwxrws--- 4 u0_a332 ext_data_rw  3452 2023-08-18 12:15 .
drwxrws--- 3 u0_a332 ext_data_rw  3452 2023-08-18 12:01 ..
drwx--S--- 4 u0_a332 ext_data_rw  3452 2023-08-18 12:01 .local
-rw-rw---- 1 u0_a332 ext_data_rw 11288 2023-08-18 12:15 benchmark.tic
-rw-rw---- 1 u0_a332 ext_data_rw 18067 2023-08-18 12:15 bpp.tic
drwx--S--- 2 u0_a332 ext_data_rw  3452 2023-08-18 12:15 bunny
-rw-rw---- 1 u0_a332 ext_data_rw  8186 2023-08-18 12:15 car.tic
-rw-rw---- 1 u0_a332 ext_data_rw  1718 2023-08-18 12:15 fire.tic
-rw-rw---- 1 u0_a332 ext_data_rw  4452 2023-08-18 12:15 font.tic
-rw-rw---- 1 u0_a332 ext_data_rw  1957 2023-08-18 12:15 music.tic
-rw-rw---- 1 u0_a332 ext_data_rw  2852 2023-08-18 12:15 p3d.tic
-rw-rw---- 1 u0_a332 ext_data_rw  2856 2023-08-18 12:15 palette.tic
-rw-rw---- 1 u0_a332 ext_data_rw 64160 2023-08-18 12:15 quest.tic
-rw-rw---- 1 u0_a332 ext_data_rw   633 2023-08-18 12:15 sfx.tic
-rw-rw---- 1 u0_a332 ext_data_rw 25218 2023-08-18 12:15 tetris.tic
```

IIUC, most of those things are a result of having run the `demo` command at the prompt in the app.

@bztsrc Your idea seems to have been a good one!

**Comment by zettelmuseum** [comment]
I can also confirm that the changed line suggested above is working. Without that change, tic80 says "cart test.lua saved" but the folder remains empty.realme c30 android 11

**Comment by nesbox** [comment]
So, at least we can add this change from @bztsrc 
``` diff
        strcpy(appFolder, SDL_AndroidGetExternalStoragePath());
        const char AppFolder[] = "/" TIC_NAME "/";
        strcat(appFolder, AppFolder);
-        mkdir(appFolder, 0700);
+        mkdir(appFolder, 0777);
```

**Comment by Timofei302** [comment]
> Итак, по крайней мере, мы можем добавить это изменение из @bztsrc
> 
> ```diff
>         strcpy(appFolder, SDL_AndroidGetExternalStoragePath());
>         const char AppFolder[] = "/" TIC_NAME "/";
>         strcat(appFolder, AppFolder);
> -        mkdir(appFolder, 0700);
> +        mkdir(appFolder, 0777);
> ```

We are waiting for changes in the code.

**Comment by zettelmuseum** [comment]
The demo command creates some files in /bunny which are still invisible. Which makedir might be responsible for this..i see another 0700 in fs.c...?

Related note:  files in /Android/data/ are only accessible by apps which use SAF on unrooted Android 11+. The folder itself is not accessible anymore (SAF uses 'virtual' folders).

Even more tangential note: Termux api recently added SAF support. But it's not in the latest official build.

**Comment by sogaiu** [comment]
> The demo command creates some files in /bunny which are still invisible.

Ah right.  I took a look and that is the case here too.

**Comment by zettelmuseum** [comment]
@sogaiu yes. I just tried changing that line and now the files in /bunny are visible (you have to uninstall first)

**Comment by sogaiu** [comment]
@zettelmuseum Thanks for trying and reporting back.

Good point about the uninstalling -- I almost forgot (^^;

For future readers, the following diff represents the changes I tried (N.B. I went for `770` instead of `777`):

```diff
diff --git a/src/studio/fs.c b/src/studio/fs.c
index 83492be6..110d6641 100644
--- a/src/studio/fs.c
+++ b/src/studio/fs.c
@@ -192,7 +192,7 @@ typedef char FsString;
 #define tic_stat stat
 #define tic_remove remove
 #define tic_fopen fopen
-#define tic_mkdir(name) mkdir(name, 0700)
+#define tic_mkdir(name) mkdir(name, 0770)
 #define tic_strncpy strncpy
 #define tic_strncat strncat
 
diff --git a/src/system/sdl/main.c b/src/system/sdl/main.c
index 6615e1fa..07d7eb2c 100644
--- a/src/system/sdl/main.c
+++ b/src/system/sdl/main.c
@@ -1323,7 +1323,7 @@ static const char* getAppFolder()
         strcpy(appFolder, SDL_AndroidGetExternalStoragePath());
         const char AppFolder[] = "/" TIC_NAME "/";
         strcat(appFolder, AppFolder);
-        mkdir(appFolder, 0700);
+        mkdir(appFolder, 0770);
 
 #else
```

That seemed to do the trick here.

Regarding:

> Android 13 further locked down /Android/data which blocks even SAF. So in the long term it might be better to give the Tic80 apk All Files Access permission and save somewhere else.

Specifically in my case, I tested on a device with Android 13.

I realize that exactly what is supported on devices can vary quite a bit (first-hand sufferring over the years) and though this might work for some people, may be it won't for others.

**Comment by bztsrc** [comment]
You're right, this has to be changed on `tic_mkdir` too!

> (Actually, what I tried was 770, though I imagine 777 -- the original suggestion -- should work too.)

The difference is: 0700 means the directory's owner can read, write and list directory entries. 0770 means the directory's owner, as well as users in the same group as the owner can do these. 0777 means everybody can do these, regardless their group assignments.

I guess on your phone adb's user is in the same group as your phone's user, that's why 0770 worked. However I can easily imagine that this isn't always the case, so I'm still suggesting 0777 instead, aka. read, write, list for all users. This way it is guaranteed that adb can access this directory.

So
```diff
diff --git a/src/studio/fs.c b/src/studio/fs.c
index 83492be6..110d6641 100644
--- a/src/studio/fs.c
+++ b/src/studio/fs.c
@@ -192,7 +192,7 @@ typedef char FsString;
 #define tic_stat stat
 #define tic_remove remove
 #define tic_fopen fopen
-#define tic_mkdir(name) mkdir(name, 0700)
+#define tic_mkdir(name) mkdir(name, 0777)
 #define tic_strncpy strncpy
 #define tic_strncat strncat
 
diff --git a/src/system/sdl/main.c b/src/system/sdl/main.c
index 6615e1fa..07d7eb2c 100644
--- a/src/system/sdl/main.c
+++ b/src/system/sdl/main.c
@@ -1323,7 +1323,7 @@ static const char* getAppFolder()
         strcpy(appFolder, SDL_AndroidGetExternalStoragePath());
         const char AppFolder[] = "/" TIC_NAME "/";
         strcat(appFolder, AppFolder);
-        mkdir(appFolder, 0700);
+        mkdir(appFolder, 0777);
 
 #else
```
Should fix it on all phones.

Cheers,
bzt

**Comment by sogaiu** [comment]
> 0777 means everybody can do these, regardless their group assignments.

Yeah, if this were an ordinary UNIXy environment, I think I'd shy away from `0777`.  Wasn't so sure for Android.

**Comment by nesbox** [comment]
I fixed access rights here 388074e4584e3f9350dbbfca73cbdf62146448c2
Let's see if it helps us

**Comment by matdombrock** [comment]
I'm still unable to access the files with the latest version. 

Termux says permission denied when attempting to access them:
```
/storage/emulated/0/android/data/com.nesbox.tic/files/TIC-80/: Permission denied
```

Phone is Nothing Phone (1)

**Comment by sogaiu** [comment]
FWIW, adb access as described [here](https://github.com/nesbox/TIC-80/issues/2222#issuecomment-1683282169) still seems to work for [this release](https://github.com/nesbox/TIC-80/releases/tag/v1.1.2837).

Regarding access via termux, I didn't have any luck either -- possibly it's what was mentioned [here](https://github.com/nesbox/TIC-80/issues/2222#issuecomment-1685245801):

> Edit: Android 13 further locked down /Android/data which blocks even SAF. So in the long term it might be better to give the Tic80 apk All Files Access permission and save somewhere else.

FWIW, Android version here is 14.

**Comment by matdombrock** [comment]
I agree that this issue is related to the Android version being used. Android versions 11+ [will prevent access to `Android/data`](https://developer.android.com/about/versions/11/privacy/storage) which is where the TIC-80 files are stored on my device. 

Aside from breaking the ability to export, this also breaks my desired workflow of cloning my projects repo into TIC-80 directory. 

FWIW my work around has been to use an old file browser app targeting an ancient Android API that can (somewhat) bypass these restrictions. But that involves manually moving files and I can't use git. I can't come up with a better solution that doesn't involve ADB or root. 

Reading above this seems that TIC uses [SDL_AndroidGetExternalStoragePath](https://github.com/nesbox/TIC-80/blob/main/src/system/sdl/main.c#L1321). I **understand that the actual "bug" here is with on the side of my OEM.**  That being said, this seems to be an issue that is both somewhat common and also pretty difficult to work around. 

_I personally think addressing this problem on the TIC-80 side would be beneficial to the user base. It effectively ruins any usefulness of the Android app for many people and there is no reasonable work around for the end user._

**Comment by sogaiu** [comment]
I noticed there is another related [issue](https://github.com/nesbox/TIC-80/issues/2470) that looks to be in the same neighborhood.

> I personally think addressing this problem on the TIC-80 side would be beneficial to the user base. 

I agree it would be beneficial.  Don't know enough detail to have an opinion on what's practical though (^^;
