### ISSUE TITLE
BT Keyboard Focus On Android Version

### ISSUE THREAD

**Issue by hseiken** [nesbox/TIC-80#60]
Current BT keyboard operation combats with new onscreen keyboard option.  When typing with BT keyboard, app doesn't auto focus for it.  It seems to recognize arrow keys, but any character keys are ignored.  Requires activating screen keyboard for BT keyboard to get proper focus.  However, focus is not retained when switching between console or editing screens.

Expected style of operation:  character keys recognized from where they came from, changing focus immediately to that keyboard (i.e. touch screen with BT connected brings up software keyboard, pushing button or connecting BT changes focus to BT keyboard from software keyboard.

**Comment by nesbox** [comment]
I've finally bought BT keyboard, will try to fix :)

**Comment by 1000tongues** [comment]
I have keyboard issues on Android as well - I can type fine when first starting the app, load any demo cart or create a new, edit code etc. After I've run a cart once, only the keyboard arrow keys and return work, as well as both soft and physical back-button. meaning I can eg. press up-arrow and return to run again. But not enter any text.

This is on Android 6.0.1, tested using physical BT keyboard, built-in soft keyboard, Swype, and Hacker's Keyboard.

**Comment by hseiken** [comment]
Rotating into portrait and tapping blank space restores functionality for all inputs after any state change of the console, such as going into/out of code editor, going into/out of game, etc.  Tapping on blank space at this point resets input.  

Hope this helps maintain some sanity while the software is developed.

**Comment by nesbox** [comment]
I removed `SDL_StopTextInput()` at all here 78f0222
so, text input will be disabled only if you hide screen keyboard manually

could please someone test it? [tic80_keyboard_fix.zip](https://github.com/nesbox/TIC-80/files/1565977/tic80_keyboard_fix.zip)

thanks

**Comment by nesbox** [comment]
[tic80_keyboard_fix.zip](https://github.com/nesbox/TIC-80/files/1584720/tic80_keyboard_fix.zip)
done

**Comment by pcornier** [comment]
I tested and it fixes all the keyboard problems i had. Is there any chance for your fix to be included in the latest pro release?

**Comment by tobi** [comment]
This problem is still present on chromebooks today. Verified with the Android TIC80 version 0.80.1330 installed from the play store. Chromebook is a Pixelbook Go that comes with a touch screen. 

After starting only the arrow keys, enter, z, x keys work. My sense is that this error comes from the wrong assumption that its running on a phone. Another indication is that it shows the touch screen overlays when running a game. 

However, if you put TIC80 into windowed mode and put it into a vertical window size like a phone, you can see a little softkeyboard icon at the bottom. If you click that the keyboard will work fine until the TIC80 screen looses focus.

**Comment by nesbox** [comment]
The man problem I don't know what to do when app loses focus, I show the keyboard icon in the case with the screen keyboard, a user can tap it and keyboard will be shown.
The question is what to do on systems without screen keyboard?
